import { useState, useMemo } from 'react';

const LEGAL_SECTIONS = [
  {
    id: 'terms',
    title: 'Terms of Use & End User License Agreement (EULA)',
    content: `
      <strong>1. ACCEPTANCE OF TERMS</strong>
      By accessing or using the Sudarshan AI platform ("Platform"), you agree to be bound by these Terms of Use and EULA. If you do not agree to these terms, you are strictly prohibited from using the Platform.

      <strong>2. LIMITATION OF LIABILITY & INDEMNIFICATION</strong>
      To the maximum extent permitted by applicable Indian law, including the Information Technology Act, 2000, the Platform is provided on an "AS-IS" and "AS-AVAILABLE" basis. Sudarshan AI, its developers, operators, and affiliates shall bear NO LIABILITY for any direct, indirect, incidental, consequential, or punitive damages arising from the use of, or inability to use, the guidance provided. You agree to indemnify and hold harmless the operators from any claims arising out of your actions taken based on the Platform's outputs.

      <strong>3. NO WARRANTY</strong>
      We make no representations or warranties, express or implied, regarding the absolute accuracy, completeness, or legal standing of the information provided by the AI models.

      <strong>4. PROHIBITED ACTIVITIES</strong>
      Users are strictly prohibited from:
      a) Attempting to reverse engineer, decompile, or bypass the Platform's security mechanisms.
      b) Utilizing the Platform to orchestrate cyberattacks, generate malicious code, or conduct unlawful reconnaissance.
      c) Providing inputs that violate the laws of the Republic of India.

      <strong>5. GOVERNING LAW & JURISDICTION</strong>
      These terms shall be governed by and construed in accordance with the laws of India. Any disputes arising out of these terms shall be subject to the exclusive jurisdiction of the competent courts located in Maharashtra, India.
    `
  },
  {
    id: 'privacy',
    title: 'Privacy Policy & Data Processing Agreement',
    content: `
      <strong>1. ZERO-RETENTION ARCHITECTURE</strong>
      Sudarshan AI operates on a strict zero-retention policy for conversational data. Your chat history is processed in volatile memory and stored locally on your device via \`sessionStorage\`. We do not persistently store, log, or database your chat interactions on our servers.

      <strong>2. DATA COLLECTION & USAGE</strong>
      We do not collect Personally Identifiable Information (PII) or Sensitive Personal Data or Information (SPDI) unless explicitly submitted via the Contact form. Any such data is processed strictly in accordance with the Digital Personal Data Protection Act, 2023 (DPDPA).

      <strong>3. THIRD-PARTY PROCESSORS</strong>
      To provide conversational intelligence, sanitized prompts are transmitted via encrypted channels (TLS 1.2+) to our designated Large Language Model (LLM) providers via their enterprise APIs. These providers are strictly contractually bound to not use API inputs for model training.

      <strong>4. PROHIBITION OF SENSITIVE CREDENTIALS</strong>
      For your absolute safety, you must NEVER input passwords, OTPs, PINs, CVVs, or active Authentication Tokens into the Platform. Our redaction engine attempts to filter such data, but the ultimate responsibility for data hygiene rests entirely with the user.
    `
  },
  {
    id: 'ai-disclaimer',
    title: 'Artificial Intelligence Limitations Disclaimer',
    content: `
      <strong>1. NATURE OF SERVICE</strong>
      Sudarshan AI utilizes Generative Artificial Intelligence to analyze contexts and propose guidance. It is an educational and decision-support copilot, not an infallible oracle.

      <strong>2. POTENTIAL FOR INACCURACIES (HALLUCINATIONS)</strong>
      AI models operate on probabilistic text generation. Consequently, the Platform may generate outputs that are contextually plausible but factually incorrect or legally outdated. 

      <strong>3. REQUIREMENT FOR INDEPENDENT VERIFICATION</strong>
      You acknowledge that you must independently verify any critical operational, legal, or technical advice provided by the Platform before executing recovery operations, configuring firewalls, or engaging with third parties.
    `
  },
  {
    id: 'cyber-disclaimer',
    title: 'Cybersecurity & Emergency Response Disclaimer',
    content: `
      <strong>1. NO LEGAL COUNSEL</strong>
      The outputs generated by Sudarshan AI regarding Indian Penal Laws (e.g., BNS) or Cyber Laws (e.g., IT Act 2000) are purely for educational orientation. They DO NOT constitute formal legal advice, and no attorney-client relationship is established through your use of the Platform.

      <strong>2. NO EMERGENCY INCIDENT RESPONSE</strong>
      Sudarshan AI is not a Digital Forensics Incident Response (DFIR) service, nor is it affiliated with Law Enforcement Agencies. The Platform cannot automatically freeze bank accounts, execute takedowns, or initiate official police investigations.

      <strong>3. MANDATORY REPORTING</strong>
      If you are facing an active financial fraud emergency, cease interacting with the AI and IMMEDIATELY call the National Cyber Crime Helpline at <strong>1930</strong> or visit <strong>cybercrime.gov.in</strong>. Corporate entities must report significant breaches directly to CERT-In (incident@cert-in.org.in) as per the statutory directives.
    `
  }
];

function LegalPage() {
  const [searchTerm, setSearchTerm] = useState('');

  // Filter sections based on search
  const filteredSections = useMemo(() => {
    if (!searchTerm.trim()) return LEGAL_SECTIONS;
    const lowerSearch = searchTerm.toLowerCase();
    return LEGAL_SECTIONS.filter(
      section => 
        section.title.toLowerCase().includes(lowerSearch) || 
        section.content.toLowerCase().includes(lowerSearch)
    );
  }, [searchTerm]);

  return (
    <section className="page page-legal">
      <div className="legal-header-banner">
        <h1 className="page-title">Legal Center</h1>
        <div className="legal-meta">
          <span className="version-pill">Version 1.0.0</span>
          <span className="date-pill">Effective Date: June 2026</span>
        </div>
        <p className="legal-subtitle">
          Transparent documentation regarding your rights, our policies, and the limitations of the Sudarshan AI platform.
        </p>
      </div>

      <div className="legal-search-container glass-card">
        <svg className="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <circle cx="11" cy="11" r="8"></circle>
          <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
        </svg>
        <input 
          type="text" 
          className="legal-search-input" 
          placeholder="Search policies, terms, or disclaimers..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="legal-content">
        {filteredSections.length === 0 ? (
          <div className="legal-empty glass-card">
            <p>No legal clauses match your search for "{searchTerm}".</p>
            <button className="ghost-btn" onClick={() => setSearchTerm('')}>Clear Search</button>
          </div>
        ) : (
          filteredSections.map(section => (
            <details 
              key={section.id} 
              className="legal-accordion glass-card"
              open={searchTerm.trim().length > 0} // Auto-expand if searching
            >
              <summary className="legal-accordion-title">
                <h2>{section.title}</h2>
                <svg className="accordion-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polyline points="6 9 12 15 18 9"></polyline>
                </svg>
              </summary>
              <div 
                className="legal-accordion-body" 
                dangerouslySetInnerHTML={{ __html: section.content }}
              />
            </details>
          ))
        )}
      </div>
    </section>
  );
}

export default LegalPage;
